/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponce } from './models/book-responce';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponce } from './models/feedback-responce';
export type { PageResponceBookResponce } from './models/page-responce-book-responce';
export type { PageResponceBorrowedBookResponse } from './models/page-responce-borrowed-book-response';
export type { PageResponceFeedbackResponce } from './models/page-responce-feedback-responce';
export type { RegistrationRequest } from './models/registration-request';
