/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { activateAccount } from '../fn/authentication/activate-account';
import { ActivateAccount$Params } from '../fn/authentication/activate-account';
import { AuthenticationResponse } from '../models/authentication-response';
import { getAllUsers } from '../fn/authentication/get-all-users';
import { GetAllUsers$Params } from '../fn/authentication/get-all-users';
import { loginUser } from '../fn/authentication/login-user';
import { LoginUser$Params } from '../fn/authentication/login-user';
import { registerUser } from '../fn/authentication/register-user';
import { RegisterUser$Params } from '../fn/authentication/register-user';


@Injectable({ providedIn: 'root' })
export class AuthenticationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  static readonly RegisterUserPath = '/auth/register';

  registerUser$Response(params: RegisterUser$Params, context?: HttpContext): Observable<StrictHttpResponse<{}>> {
    return registerUser(this.http, this.rootUrl, params, context);
  }

  registerUser(params: RegisterUser$Params, context?: HttpContext): Observable<{}> {
    return this.registerUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>) => r.body)
    );
  }

  static readonly LoginUserPath = '/auth/authenticate';

  loginUser$Response(params: LoginUser$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthenticationResponse>> {
    return loginUser(this.http, this.rootUrl, params, context);
  }

  loginUser(params: LoginUser$Params, context?: HttpContext): Observable<AuthenticationResponse> {
    return this.loginUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<AuthenticationResponse>) => r.body)
    );
  }

  static readonly GetAllUsersPath = '/auth/getallusers';

  getAllUsers$Response(params?: GetAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<{}>> {
    return getAllUsers(this.http, this.rootUrl, params, context);
  }

  getAllUsers(params?: GetAllUsers$Params, context?: HttpContext): Observable<{}> {
    return this.getAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<{}>) => r.body)
    );
  }

  static readonly ActivateAccountPath = '/auth/activate-account';

  activateAccount$Response(params: ActivateAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return activateAccount(this.http, this.rootUrl, params, context);
  }

  activateAccount(params: ActivateAccount$Params, context?: HttpContext): Observable<void> {
    return this.activateAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>) => r.body)
    );
  }
}
