/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveReturnBook } from '../fn/book/approve-return-book';
import { ApproveReturnBook$Params } from '../fn/book/approve-return-book';
import { BookResponce } from '../models/book-responce';
import { borrowBook } from '../fn/book/borrow-book';
import { BorrowBook$Params } from '../fn/book/borrow-book';
import { findAllBooks } from '../fn/book/find-all-books';
import { FindAllBooks$Params } from '../fn/book/find-all-books';
import { findAllBooksByOwner } from '../fn/book/find-all-books-by-owner';
import { FindAllBooksByOwner$Params } from '../fn/book/find-all-books-by-owner';
import { findAllBorrowedBooks } from '../fn/book/find-all-borrowed-books';
import { FindAllBorrowedBooks$Params } from '../fn/book/find-all-borrowed-books';
import { findAllReturnedBooks } from '../fn/book/find-all-returned-books';
import { FindAllReturnedBooks$Params } from '../fn/book/find-all-returned-books';
import { findBookById } from '../fn/book/find-book-by-id';
import { FindBookById$Params } from '../fn/book/find-book-by-id';
import { PageResponceBookResponce } from '../models/page-responce-book-responce';
import { PageResponceBorrowedBookResponse } from '../models/page-responce-borrowed-book-response';
import { returnBook } from '../fn/book/return-book';
import { ReturnBook$Params } from '../fn/book/return-book';
import { saveBook } from '../fn/book/save-book';
import { SaveBook$Params } from '../fn/book/save-book';
import { updateArchivedStatus } from '../fn/book/update-archived-status';
import { UpdateArchivedStatus$Params } from '../fn/book/update-archived-status';
import { updateSHarableStatus } from '../fn/book/update-s-harable-status';
import { UpdateSHarableStatus$Params } from '../fn/book/update-s-harable-status';
import { uploadBookCover } from '../fn/book/upload-book-cover';
import { UploadBookCover$Params } from '../fn/book/upload-book-cover';

@Injectable({ providedIn: 'root' })
export class BookService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findAllBooks()` */
  static readonly FindAllBooksPath = '/books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooks$Response(params?: FindAllBooks$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponceBookResponce>> {
    const obs = findAllBooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooks(params?: FindAllBooks$Params, context?: HttpContext): Promise<PageResponceBookResponce> {
    const resp = this.findAllBooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponceBookResponce>): PageResponceBookResponce => r.body);
  }

  /** Path part for operation `saveBook()` */
  static readonly SaveBookPath = '/books';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveBook()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBook$Response(params: SaveBook$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = saveBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveBook$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveBook(params: SaveBook$Params, context?: HttpContext): Promise<number> {
    const resp = this.saveBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `uploadBookCover()` */
  static readonly UploadBookCoverPath = '/books/cover/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadBookCover()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadBookCover$Response(params: UploadBookCover$Params, context?: HttpContext): Promise<StrictHttpResponse<{
}>> {
    const obs = uploadBookCover(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadBookCover$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  uploadBookCover(params: UploadBookCover$Params, context?: HttpContext): Promise<{
}> {
    const resp = this.uploadBookCover$Response(params, context);
    return resp.then((r: StrictHttpResponse<{
}>): {
} => r.body);
  }

  /** Path part for operation `borrowBook()` */
  static readonly BorrowBookPath = '/books/borrow/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `borrowBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowBook$Response(params: BorrowBook$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = borrowBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `borrowBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  borrowBook(params: BorrowBook$Params, context?: HttpContext): Promise<number> {
    const resp = this.borrowBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `updateSHarableStatus()` */
  static readonly UpdateSHarableStatusPath = '/books/shaeabled/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateSHarableStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSHarableStatus$Response(params: UpdateSHarableStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = updateSHarableStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateSHarableStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateSHarableStatus(params: UpdateSHarableStatus$Params, context?: HttpContext): Promise<number> {
    const resp = this.updateSHarableStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `returnBook()` */
  static readonly ReturnBookPath = '/books/borrow/return/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `returnBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBook$Response(params: ReturnBook$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = returnBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `returnBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  returnBook(params: ReturnBook$Params, context?: HttpContext): Promise<number> {
    const resp = this.returnBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `approveReturnBook()` */
  static readonly ApproveReturnBookPath = '/books/borrow/return/approve/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveReturnBook()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBook$Response(params: ApproveReturnBook$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = approveReturnBook(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveReturnBook$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveReturnBook(params: ApproveReturnBook$Params, context?: HttpContext): Promise<number> {
    const resp = this.approveReturnBook$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `updateArchivedStatus()` */
  static readonly UpdateArchivedStatusPath = '/books/archived/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateArchivedStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus$Response(params: UpdateArchivedStatus$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = updateArchivedStatus(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateArchivedStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  updateArchivedStatus(params: UpdateArchivedStatus$Params, context?: HttpContext): Promise<number> {
    const resp = this.updateArchivedStatus$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `findBookById()` */
  static readonly FindBookByIdPath = '/books/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findBookById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookById$Response(params: FindBookById$Params, context?: HttpContext): Promise<StrictHttpResponse<BookResponce>> {
    const obs = findBookById(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findBookById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findBookById(params: FindBookById$Params, context?: HttpContext): Promise<BookResponce> {
    const resp = this.findBookById$Response(params, context);
    return resp.then((r: StrictHttpResponse<BookResponce>): BookResponce => r.body);
  }

  /** Path part for operation `findAllReturnedBooks()` */
  static readonly FindAllReturnedBooksPath = '/books/returned';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllReturnedBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedBooks$Response(params?: FindAllReturnedBooks$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponceBorrowedBookResponse>> {
    const obs = findAllReturnedBooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllReturnedBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllReturnedBooks(params?: FindAllReturnedBooks$Params, context?: HttpContext): Promise<PageResponceBorrowedBookResponse> {
    const resp = this.findAllReturnedBooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponceBorrowedBookResponse>): PageResponceBorrowedBookResponse => r.body);
  }

  /** Path part for operation `findAllBooksByOwner()` */
  static readonly FindAllBooksByOwnerPath = '/books/owner';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBooksByOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooksByOwner$Response(params?: FindAllBooksByOwner$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponceBookResponce>> {
    const obs = findAllBooksByOwner(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBooksByOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBooksByOwner(params?: FindAllBooksByOwner$Params, context?: HttpContext): Promise<PageResponceBookResponce> {
    const resp = this.findAllBooksByOwner$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponceBookResponce>): PageResponceBookResponce => r.body);
  }

  /** Path part for operation `findAllBorrowedBooks()` */
  static readonly FindAllBorrowedBooksPath = '/books/borrowed';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllBorrowedBooks()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedBooks$Response(params?: FindAllBorrowedBooks$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponceBorrowedBookResponse>> {
    const obs = findAllBorrowedBooks(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllBorrowedBooks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllBorrowedBooks(params?: FindAllBorrowedBooks$Params, context?: HttpContext): Promise<PageResponceBorrowedBookResponse> {
    const resp = this.findAllBorrowedBooks$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponceBorrowedBookResponse>): PageResponceBorrowedBookResponse => r.body);
  }

}
