/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findFeedbackByBookId } from '../fn/feedback/find-feedback-by-book-id';
import { FindFeedbackByBookId$Params } from '../fn/feedback/find-feedback-by-book-id';
import { PageResponceFeedbackResponce } from '../models/page-responce-feedback-responce';
import { saveFeedback } from '../fn/feedback/save-feedback';
import { SaveFeedback$Params } from '../fn/feedback/save-feedback';

@Injectable({ providedIn: 'root' })
export class FeedbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `saveFeedback()` */
  static readonly SaveFeedbackPath = '/feedbacks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback$Response(params: SaveFeedback$Params, context?: HttpContext): Promise<StrictHttpResponse<number>> {
    const obs = saveFeedback(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveFeedback(params: SaveFeedback$Params, context?: HttpContext): Promise<number> {
    const resp = this.saveFeedback$Response(params, context);
    return resp.then((r: StrictHttpResponse<number>): number => r.body);
  }

  /** Path part for operation `findFeedbackByBookId()` */
  static readonly FindFeedbackByBookIdPath = '/feedbacks/book/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findFeedbackByBookId()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFeedbackByBookId$Response(params: FindFeedbackByBookId$Params, context?: HttpContext): Promise<StrictHttpResponse<PageResponceFeedbackResponce>> {
    const obs = findFeedbackByBookId(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findFeedbackByBookId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFeedbackByBookId(params: FindFeedbackByBookId$Params, context?: HttpContext): Promise<PageResponceFeedbackResponce> {
    const resp = this.findFeedbackByBookId$Response(params, context);
    return resp.then((r: StrictHttpResponse<PageResponceFeedbackResponce>): PageResponceFeedbackResponce => r.body);
  }

}
