spring.application.name=Book-Social-Network
spring.datasource.url=jdbc:postgresql://localhost:5433/book_social_network
spring.datasource.username=username

spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=ali
spring.mail.password=ali
spring.mail.properties.mail.smtp.trust="*"
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=5000
spring.mail.properties.mail.writetimeout=5000


application.security.jwt.secret=mfklsdmfmanm32noiwefiosf9whfionIIUHUIHDUAHWUIH

application.security.jwt.secret-key=mfklsdmfmanm32noiwefiosf9whfionIIUHUIHDUAHWUIH
application.security.jwt.expiration=86400000
application.file.upload.photos-output-path=./uploads
application.mailing.frontend-activation-url=http://localhost:4200/activate-account
